curious/api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

curious/curious/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Examples:
    # url(r'^$', 'curious.views.home', name='home'),
    # url(r'^blog/', include('blog.urls'))
    url(r'^', include('curiousWorkbench.urls',namespace="curiousWorkbench")),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/$', include('registration.backends.default.urls')),
    url(r'^accounts/$', include('registration.backends.default.urls')),
    url(r'^accounts/$', include('django.contrib.auth.urls')),
    url(r'^curiousWorkbench/', include('curiousWorkbench.urls',namespace="curiousWorkbench")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

curious/curiousWorkbench/urls.py
import sys
import os
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

dir_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(dir_path)

from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView

import views
import viewFacebook
import viewSlack
from viewFacebook import fbClientAriseBotView
from viewSlack import slackClientWalnutBotView


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/', views.user_signup, name="user_signup"),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/$', include('registration.backends.default.urls')),
    url(r'^accounts/$', include('registration.backends.default.urls')),
    url(r'^accounts/$', include('django.contrib.auth.urls')),
    url(r'^login/', views.user_login, name="user_login"),
    url(r'^successfullInstall/', views.successfullInstall, name="successfullInstall"),
    url(r'^webHome/', views.webHome, name="webHome"),
    url(r'^webManageModule/', views.webHome, name="webHome"),
    url(r'^logout/', views.user_logout, name="user_logout"),
    url(r'^fbABWCV/(?P<content_Id>\d+)/(?P<user_Id>\w+)/$', views.fbAriseBotContentWebView, name='fbAriseBotContentWebView'),
    url(r'^myProfile/(?P<userID>\w+)/$', views.fbAriseBotCertWebView, name='fbAriseBotCertWebView'),
    url(r'^analytics/(?P<userID>\w+)/$', views.fbAriseBotCertWebView, name='fbAriseBotCertWebView'),
    url(r'^displayPVPolicy/', views.displayPVPolicy, name="displayPVPolicy"),
    url(r'^displayTnC/', views.displayTnC, name="displayTnC"),
    url(r'^fbABReminder/(?P<passID>\d+)/$', views.fbAriseBotReminder,name='fbAriseBotReminder'),
    url(r'^configUsers/', views.configUsers, name='configUsers'),
    url(r'^configSettings/', views.configSettings, name='configSettings'),
    url(r'^saveSettings/', views.saveSettings, name='saveSettings'),
    url(r'^configBot/', views.configBot, name='configBot'),
    url(r'^configStateMachine/', views.configStateMachine, name='configStateMachine'),
    url(r'^addStateMachineSubscription/', views.addStateMachineSubscription, name='addStateMachineSubscription'),
    url(r'^deleteStateMachineSubscription/(?P<SM_ID>\d+)/$', views.deleteStateMachineSubscription, name='deleteStateMachineSubscription'),
    url(r'^editStateMachineSubscription/(?P<SM_ID>\d+)/$', views.editStateMachineSubscription, name='editStateMachineSubscription'),
    url(r'^editTestChat/', views.editTestChat, name='editTestChat'),
    url(r'^editContentLibrary/(?P<ID>\d+)/$', views.editContentLibrary, name='editContentLibrary'),
    url(r'^deleteContentLibrary/(?P<ID>\d+)/$', views.deleteContentLibrary, name='deleteContentLibrary'),
    url(r'^configMessageLibrary/', views.configMessageLibrary, name='configMessageLibrary'),
    url(r'^editMessageLibrary/(?P<ID>\d+)/$', views.editMessageLibrary, name='editMessageLibrary'),
    url(r'^deleteMessageLibrary/(?P<ID>\d+)/$', views.deleteMessageLibrary, name='deleteMessageLibrary'),
    url(r'^addMessageLibrary/', views.addMessageLibrary, name='addMessageLibrary'),
    url(r'^configContentLibrary/', views.configContentLibrary, name='configContentLibrary'),
    url(r'^editContentLibrary/(?P<ID>\d+)/$', views.editContentLibrary, name='editContentLibrary'),
    url(r'^deleteContentLibrary/(?P<ID>\d+)/$', views.deleteContentLibrary, name='deleteContentLibrary'),
    url(r'^addContentLibrary/', views.addContentLibrary, name='addContentLibrary'),
    url(r'^saveStateMachine/(?P<SM_ID>\d+)/$', views.saveStateMachine, name='saveStateMachine'),
    url(r'^saveStateMachine/', views.saveStateMachine, name='saveStateMachine'),
    url(r'^saveMessageLibrary/(?P<ID>\d+)/$', views.saveMessageLibrary, name='saveMessageLibrary'),
    url(r'^saveMessageLibrary', views.saveMessageLibrary, name='saveMessageLibrary'),
    url(r'^saveContentLibrary/(?P<ID>\d+)/$', views.saveContentLibrary, name='saveContentLibrary'),
    url(r'^saveContentLibrary/', views.saveContentLibrary, name='saveContentLibrary'),
    url(r'^handleActions/', views.handleActions, name='handleActions'),
    url(r'^configModule/', views.configModule, name='configModule'),
    url(r'^topics/', views.configModule, name='configModule'),
    url(r'^uploadContent/(?P<ModuleID>\d+)/$', views.uploadContent, name='uploadContent'),
    url(r'^editModule/(?P<ID>\d+)/$', views.editModule, name='editModule'),
    url(r'^deleteModule/(?P<ID>\d+)/$', views.deleteModule, name='deleteModule'),
    url(r'^addModule/', views.addModule, name='addModule'),
    url(r'^saveModule/(?P<ID>\d+)/$', views.saveModule, name='saveModule'),
    url(r'^saveModule/', views.saveModule, name='saveModule'),
    url(r'^slackWebhookWalnutBot/$', viewSlack.slackClientWalnutBotView.as_view()),
    url(r'^fbWebhookAriseBot/$', viewFacebook.fbClientAriseBotView.as_view() ),
    url(r'^slackAuth/$', views.slackAuth, name="slackAuth"),

]

curious/curiousWorkbench/views.py
import sys
import os
import datetime
from django.db.models import Count
import ast

dir_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(dir_path)
import csv
from django.db import transaction
from viewSlack import slackClientWalnutBotView
from django.contrib.auth.models import AnonymousUser
#sys.path.append(dir_path + "/customViews")
from django.views.decorators.csrf import requires_csrf_token
import magic
from random import randint
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.views.decorators.csrf import ensure_csrf_cookie
from django.utils.html import escape
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.context_processors import csrf
#from django.template import RequestContext, loader
from django.template import Context
from django.template.loader import get_template
from django.shortcuts import get_object_or_404, render, render_to_response
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
#from networkBuilder import Network
from django.contrib.auth import authenticate, login, logout
import pygal
from pygal.style import DefaultStyle
from pygal.style import Style
from models import UserState, UserSkillStatus
from models import StateMachine, MessageLibrary, ContentLibrary, Module, UserCertification, Progress, PlatformCredentials, Challenge, SignUp,UserActions
from botState import BotState
import urllib
import urllib2
from django.core.files.storage import FileSystemStorage
from itertools import *
from django.db import connection

import redis
import StringIO
import random
import os
import time
import sys
import json
import requests
import subprocess
from django.http import Http404, HttpResponse
import json
import requests
import random
import re
from pprint import pprint

from configSettings import configSettings
from django.views import generic
import logging

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import mixpanel
from mixpanel import Mixpanel
import plotly.plotly as py
import plotly.graph_objs as go
#import curiousWorkbench.clientFacebook


mp = Mixpanel("7a2ae593d77b3bd1b818d79ce75b69ff")


configSettingsObj = configSettings()
#----------------Logging ------------------
logger = logging.getLogger('views')
hdlr = logging.FileHandler(configSettingsObj.logFolderPath + 'views.log')
formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
hdlr.setFormatter(formatter)
logger.addHandler(hdlr)
logger.setLevel(logging.INFO)
logger.info('logging log folder path views.py')
rootURL = configSettingsObj.webUrl
# logger.info(configSettingsObj.logFolderPath)
#----------------Logging ------------------


def query_to_dicts(query_string, *query_args):
    cursor = connection.cursor()
    cursor.execute(query_string, query_args)
    col_names = [desc[0] for desc in cursor.description]
    while True:
        row = cursor.fetchone()
        if row is None:
            break
        row_dict = dict(izip(col_names, row))
        yield row_dict
    return


def fbAriseBotContentWebView(request, content_Id, user_Id):
    try:
        logger.info("1")
        mp.track(user_Id, "ViewContent", {
                 'strNextEvent': "", 'strToState': "", 'strCallFunction': "", "Content_ID": content_Id})

        strContentID = content_Id
        r_server = redis.Redis(host=configSettingsObj.inMemDbHost,
                               port=configSettingsObj.inMemDbPort, db=configSettingsObj.inMemDataDbName)
        logger.info("2")
        if strContentID != "":
            strContent = r_server.hget("KEY_CONTENT_" + strContentID, "Msg")
        else:
            strContent = r_server.hget("0", "Msg")
        strHTML = "Oop, did not find content"
        logger.info("3")
        if strHTML != "":
            dictContent = json.loads(strContent)
            try:
                selProgress = Progress.objects.get(
                    userID=user_Id, SKILL_CODE=dictContent["Skill"])
                selProgress.Credits += 1
            except Progress.DoesNotExist:
                selProgress = Progress(
                    userID=user_Id, SKILL_CODE=dictContent["Skill"])
                selProgress.Credits = 1
            selProgress.save()
            logger.info("4")
            if dictContent["Type"] == "WebPage":
                strHTML = "<iframe style='overflow: hidden; height: 100%; width: 100%; position: absolute;' src='" + \
                    dictContent["LinkURL"] + "'></iframe>"
            if dictContent["Type"] == "YouTube":
                strHTML = "<iframe style='overflow: hidden; height: 100%; width: 100%; position: absolute;' height='315' src='https://www.youtube.com/embed/" + \
                    dictContent["Embed_ID"] + "'></iframe>"
            if dictContent["Type"] == "UGC":
                strHTML = "<iframe style='overflow: hidden; height: 100%; width: 100%; position: absolute;' height='315' src='" + \
                    self.configSettingsObj.absFileLocation + "/videos/" + \
                    dictContent["LinkURL"] + "'></iframe>"
        logger.info("5")
        template = get_template('curiousWorkbench/displayContentWebView.html')
        strTitle = dictContent["Title"]
        context = RequestContext(request, {
            'rootURL' : rootURL,
            'strHTML': strHTML,
            'strTitle': strTitle,
            'timeStamp': timezone.now(),
        })
        return HttpResponse(template.render(context))
    except Exception, e:
        self.logger.error('fbAriseBotContentWebView' + str(e))


@csrf_exempt
def user_login(request):
    state = "Please log in below..."
    username = ''
    password = ''
    if request.POST:
        if 'LoginFormSubmit':
            username = request.POST["username"]
            password = request.POST["password"]

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    state = "You're successfully logged in!"
                else:
                    state = "Your account is not active, please contact the site admin."

                template = get_template('curiousWorkbench/index.html')
                context = RequestContext(request, {
                    'rootURL' : rootURL,
                    'state': state,
                })
                return HttpResponse(template.render(context))
            else:
                state = "Your username and/or password were incorrect."
                template = get_template('curiousWorkbench/login.html')
                context = RequestContext(request, {
                    'rootURL' : rootURL,
                    'state': state,
                })
                return HttpResponse(template.render(context))

    #state = "error occured."
    template = get_template('curiousWorkbench/login.html')
    context = RequestContext(request, {
        'rootURL' : rootURL,
        'state': state,
        'UserName': request.user.username,
    }
    )
    return HttpResponse(template.render(context))

@csrf_exempt
def user_signup(request):
    SignUpState=""
    userEmail=''
    if request.POST:
        if request.POST:
            state = "NA"
            userEmail = request.POST["userEmail"]
            try:
                validate_email(userEmail)
            except ValidationError as e:
                SignUpState =  "oops! invalid email id"
            else:

                userSignUpObj  = SignUp.objects.filter(UserEmail=userEmail.strip())
                if len(userSignUpObj)>0:
                    SignUpState = "You have already signed up, please wait"
                else:

                    userSignUpObj = SignUp()
                    userSignUpObj.UserEmail= userEmail
                    userSignUpObj.save()

                    SignUpState = "You have been added to the early beta, we will let you know soon"


    #state = "error occured."
    template = get_template('curiousWorkbench/login.html')
    context = RequestContext(request, {
        'rootURL' : rootURL,
        'SignUpState': SignUpState,
        'state':""

    }
    )


    # context.update(csrf(request))

    return HttpResponse(template.render(context))



@csrf_exempt
def successfullInstall(request):
    state = "Please log in below..."
    username = ''
    password = ''
    if request.POST:
        state = "here 1"
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                state = "You're successfully logged in!"
            else:
                state = "Your account is not active, please contact the site admin."

            template = get_template('curiousWorkbench/index.html')
            context = RequestContext(request, {
                'rootURL' : rootURL,
                'state': state,
            })
            return HttpResponse(template.render(context))
        else:
            state = "Your username and/or password were incorrect."
            template = get_template('curiousWorkbench/login.html')
            context = RequestContext(request, {
                'rootURL' : rootURL,
                'state': state,
            })
            return HttpResponse(template.render(context))

    #state = "error occured."
    template = get_template('curiousWorkbench/successfullInstall.html')
    context = RequestContext(request, {
        'rootURL' : rootURL,
        'state': state,
        'UserName': request.user.username,
    }
    )

curious/curiousWorkbench/templates/curiousWorkbench/addDataFolder.html
{% extends "curiousWorkbench/base.html" %}
{% load staticfiles %}
{% block Header %}My Config Model Page{% endblock %}

{% block Footer %}My Footer{% endblock %}

{% block Content %}

<form action="{% url 'curiousWorkbench:saveNewModel' %}" method="post">
{% csrf_token %}
<div class="FormHeader"><span class="Title">Edit Model</span></div>
<div class="FormRow"><span class="Label">Name:</span><span class="Value">	<input type="Text" name="modelMapName" /> </span></div>
	<div class="FormRow"><span class="Label">Description:</span><span class="Value">	<input type="Text" name="modelDescription" /> </span></div>
	<div class="FormRow"><span class="Label">Created By:</span><span class="Value">	Chandan</span></div>
<div class="FormRow"><span class="Label">Created Date:</span><span class="Value">	{{ timeStamp }}</span></div>
<div class="FormRow"><span class="Label">Raw XML:</span><span class="Value">	
<TextArea cols="100" rows="20" name="RawXML" ID="txtRawXML">
</TextArea>
</span></div>
<div class="FormFooter"><span class="Title">Save Model</span></div>

	<input type="submit" value="saveModel" />
</form>
{% endblock %}

curious/curiousWorkbench/templates/curiousWorkbench/configBot.html
{% extends "curiousWorkbench/base.html" %} {% load staticfiles %} {% block Header %}Model{% endblock %} {% block Footer %}My Footer{% endblock %} {% block Content %} {% if StateMachineList %} {% csrf_token %}


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-8">
        <h2>Config Bot</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'curiousWorkbench:index' %}">Home</a>
            </li>
            <li class="active">
                <strong>Configure Bot</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-4">
        <div class="title-action">

            <form action="{% url 'curiousWorkbench:handleActions' %}" method="post">
                {% csrf_token %}
                <span class="label label-primary pull-right;" style="float:right;"><input class="btn btn-primary"  type="submit" name="refreshBotBehaviour" value="Publish Changes" />
                  </form>
        </div></div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            <div class="ibox float-e-margins">

                <div class="ibox-content" style="height:100%;">


                    <div style="width:1200px;height:100%;float:left;">
                        <div style="width:350px;overflow-y: scroll;;height:100%;border:solid 0px;float:left">
                          <iframe id="eventList" name="EventList" src="{% url 'curiousWorkbench:configStateMachine' %}" style="float:left;width:400px;height:100%;overflow-y: scroll;border:solid 0px;">
&nbsp;
</iframe>&nbsp;&nbsp;
                        </div>
                        <div style="width:810px;overflow-y: scroll;sroll;height:100%;border:solid 0px;float:left;">
                            <iframe id="stateMachine" name="stateMachine" style="float:left;width:400px;height:100%;overflow-y: scroll;border:solid 0px;">
  </iframe>
                            <iframe id="messageWindow" name="messageWindow" src="" style="float:left;width:400px;height:100%;overflow-y: scroll;border:solid 0px;">
  </iframe>&nbsp;&nbsp;
                        </div>&nbsp;&nbsp;
                    </div>

                </div>
            </div>
        </div>

        {% else %}
        <p>No models are available.</p>

        {% endif %}
    </div>
</div>
</div>
{% endblock %}

curious/curiousWorkbench/templates/curiousWorkbench/configModel.html
{% extends "curiousWorkbench/base.html" %}
{% load staticfiles %}
{% block Header %}Model{% endblock %}

{% block Footer %}My Footer{% endblock %}

{% block Content %}
{% if modelMapList %}


<div class="FormHeader">
  <div class="Title"> Models :<span> {{ modelMapList.count }} Found </span></div>
</div>
<br>
<table>
  <tr class="TableHeader"><td width="400px" >Model Name</td><td width="200px">Description</td><td>Delete</td><td width="100px">Created By</td><td width="400px">Last Updated </td></tr>
  {% for ModelMap in modelMapList %}
  <tr class="TableRow"><td>
    <img class="Logo" src="{% static 'curiousWorkbench/images/network.png' %}" height="15px" >
    <a href="{% url 'curiousWorkbench:editModel' ModelMap.id %}" method="post" alt="{{ ModelMap.Description }}">{{ ModelMap.Name }}</a></td>
    <td>{{ ModelMap.Description }}</td>
    <td> <a href="{% url 'curiousWorkbench:deleteStateMachineSubscription' stateMachineSubscription.id %}" method="post" alt="{{ ModelMap.Description }}">delete</a> </td>
    <td>{{ ModelMap.CreatedBy }}</td><td>{{ ModelMap.Created }}</td></tr>
    {% endfor %}
  </table>

  {% else %}
  <p>No models are available.</p>

  {% endif %}
  <br><br>
  <a href="{% url 'curiousWorkbench:addStateMachineSubscription' %}">+Create New Model</a>
  {% endblock %}

curious/curiousWorkbench/templates/curiousWorkbench/configModuleold.html
{% extends "curiousWorkbench/base.html" %}
{% load staticfiles %}
{% block Header %}Modules{% endblock %}

{% block Footer %}My Footer{% endblock %}

{% block Content %}
{% if moduleList %}
<div class="form-style-5">

  <fieldset>
    <legend><span class="number">1</span>Learning Modules : <span> {{ moduleList.count }}  found </legend>
      </fieldset
      <div class="Title"></span></div></div>
      <table class="table-fill">
        <thead>
          <tr class="TableHeader">
            <th class="text-left" width="100px" >Title</th>
            <th class="text-left" width="200px">Description</th>
            <th class="text-left" width="100px">Created By</th>
            <th class="text-left" width="100px">Created</th>
            <th class="text-left" width="100px">Content</th>
            <th class="text-left" width="100px">&nbsp;</th>
            <th class="text-left" width="100px">&nbsp;</th>
          </tr></thead>
          <tbody class="table-hover">
            {% for eachModule in moduleList %}

            <tr class="TableRow">
              <td><a href="{% url 'curiousWorkbench:editModule' eachModule.id %}" method="post" alt="{{ eachModule.Description }}">{{ eachModule.Title }}</a></td>
              <td>{{ eachModule.Description }}</td>
              <td>{{ eachModule.CreatedBy }}</td>
              <td>{{ eachModule.Created }}</td>
              <td><a href="{% url 'curiousWorkbench:createConversations' eachModule.id  %}" method="post">content</a></td>
              <td><a href="{% url 'curiousWorkbench:editModule' eachModule.id  %}" method="post">edit</a></td>
              <td><a href="{% url 'curiousWorkbench:deleteModule' eachModule.id  %}" method="post">delete</a></td>

              {% endfor %}</tbody>
            </table>


            {% else %}
            <p>No Modules are available.</p>
            {% endif %}
            <br><br>
            <form action="{% url 'curiousWorkbench:configModule' %}" method="post">
              {% csrf_token %}
              <div class="FormHeader"><div class="Title"></div></div>
              <br>
              <!--
              <div class="FormRow"><div class="Label">Title:</div><div class="Value">	<input type="Text" name="moduleTitle" /> </div></div>
              <div class="FormRow"><div class="Label">Description:</div><div class="Value">	<input type="Text" name="moduleDescription" /> </div></div>
              <div class="FormRow"><div class="Label">Created By:</div><div class="Value">Chandan</div></div>
              <div class="FormRow"><div class="Label">Created Date:</div><div class="Value">	{{ timeStamp }}</div></div>
              <div class="FormRow"><div class="Label">Model:</div><div class="Value">

              <select name="selModelMap" >
              {% for KnuggetsTrainingModule in KnuggetsTrainingModules %}
              <option value="{{ KnuggetsTrainingModule.id }}">{{KnuggetsTrainingModule.Tite}}</option>
              {% endfor %}
            </select>

          </span></div>
          <div class="FormRow"><div class="Label">&nbsp;</div>
          <div class="Value"><input type="submit" value="Save Module" /></div></div>
        </div>-->

        <div class="form-style-5">

          <fieldset>
            <legend><span class="number">2</span> Create Module</legend>
            <input type="text" name="moduleTitle" placeholder="Title *">
            <input type="text" name="moduleDescription" placeholder="Description *">
            <input type="text" name="moduleCreated" placeholder="Created by *">
            <textarea name="txtCreatedBy" placeholder="Chandan"></textarea>
            <input type="submit" value="Save Module" />
          </fieldset>

        </div>
      </form>

      {% endblock %}

curious/curiousWorkbench/templates/curiousWorkbench/displayCertificateWebView.html
<html>
<head>
  <title>{{ strTitle }}</title>
</head>
{% autoescape off %}{{ strHTML }}{% endautoescape %}


<body>
</body>
</html>

curious/curiousWorkbench/templates/curiousWorkbench/exportNeuralNetwork.html
{% extends "curiousWorkbench/base.html" %}
{% load staticfiles %}


{% block Header %}Export Project{% endblock %}

{% block Content %}My Content {% endblock %}
{% block Footer %}My Footer{% endblock %}

curious/curiousWorkbench/templates/curiousWorkbench/loadData.html
{% extends "curiousWorkbench/base.html" %}
{% load staticfiles %}


{% block Header %}My Load Data Page{% endblock %}

{% block Content %}My Content {% endblock %}
{% block Footer %}My Footer{% endblock %}

curious/curiousWorkbench/templates/curiousWorkbench/uploadContent.html
{% extends "curiousWorkbench/base.html" %}
{% load staticfiles %}

{% block Header %}Modules{% endblock %}

{% block Footer %}My Footer{% endblock %}

{% block UserName %} {{UserName}} {% endblock %}
{% block Content %}
{% if ModuleList %}

 <form action="{% url 'curiousWorkbench:uploadContent' ModuleID %}" method="post" enctype="multipart/form-data">
   {% csrf_token %}
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Modules</h2>
    <ol class="breadcrumb">
                            <li>
                                <a href="{% url 'curiousWorkbench:index' %}">Home</a>
                            </li>
                            <li class="active">
                                <strong>Upload Content</strong>
                            </li>
                          </ol>
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">

      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>  {{ ModuleList.count }} Modules Found        </h5>
          <div class="ibox-tools">

            <a href="{% url 'curiousWorkbench:addModule' %}">+ New Module</a></div>

          </div>
          <div class="ibox-content">
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th  >ID</th>
                    <th  >Title</th>
                    <th  >Description</th>
                    <th >Goal</th>
                    <th >Author</th>
                    <th >Units</th>
                    </tr>

                  </thead>
                  <tbody>

                    {% for Module in ModuleList %}
                    <tr>
                      <td><a href="{% url 'curiousWorkbench:editModule' Module.ID %}" method="post" alt="{{ Module.ID }}">{{ Module.ID }}</a></td>
                      <td>{{ Module.Title }}</td>
                      <td>{{ Module.Description }}</td>
                      <td>{{ Module.Goal }}</td>
                      <td>{{ Module.Author }}</td>
                      <td>{{ Module.Units }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <input type="file" name="myfile">
             <button type="submit">Upload</button>
             {% if uploaded_file_url %}
                 <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
               {% endif %}
{% autoescape off %}
{{ dataTable }}
{% endautoescape %}
{{ SuccessMessage }}
  {% else %}

  <p>No models are available.</p>

  {% endif %}
  <br><br>
  <a href="{% url 'curiousWorkbench:addModule' %}">+Create New Content</a>
             </form>


  {% endblock %}